### ISSUE TITLE
Welcome & Introductions

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/loose-confederation#1]
Welcome to "[a loose confederation](https://twitter.com/adamhjk/status/1687113805237714944)" of people who are interested in establishing a value system for Open Source that better reflects where we are today vs. the Free Software movement of the past. Sentry's Open Source values are:

1. **sustainability** for maintainers, and
2. **access** to technology and knowledge for developers.

Read more about what this means to us and the history behind it in our blog post, [**Sentry's Open Source Values**](https://blog.sentry.io/sentrys-open-source-values/). If you share our values then let's work together to move the conversation forward. Go ahead and introduce yourself in this thread and watch the repo to stay informed and participate.

Icebreakers:

1. Who are you?
1. What company are you with?
1. What are _your_ Open Source values?

### Updates

- Sentry hosted an event, "[The Future of Open Source: SaaS, the Final Frontier](https://sentry.io/resources/the-future-of-open-source-saas-the-final-frontier/)," where we talked about some of these themes.
- OSI published "[Open Source’s lost decade](https://opensource.net/lost-decade-crucial-lessons-for-ai/)" about how Open Source did not keep up with the evolution of cloud and mobile in the tech industry.

**Comment by ljharb** [comment]
I don't use any non-OSI-approved licenses myself. However, I appreciate and share the values described in the blog post. As an open source maintainer, I certainly feel the weight of others making baffling amounts of money off of my labor without compensating me for it, and I can understand a business not wanting to find itself in the same situation.

I'd love to participate in the conversation. My "agenda" would be twofold: to ensure open source maintainers have an advocate in what will likely be an impactful effort, and to seek serendipitous ideas and solutions that could be brought back to the wider capital-lettered open source community to improve the lot of maintainers in general.

**Comment by davidarthurthomas** [comment]
Hey, what's up! Super pumped about this :)

My name is David and I'm one of the co-founders at [Tunnel](https://tunnel.dev) where we're transforming localhost into a collaborative workspace for product. We're taking a local-first approach to bringing teams together to iterate on code, experience the product, and collect feedback in one place.

Still working on our open-source values, and hoping to draw inspiration from the folks here

**Comment by ezekg** [comment]
Hey all, my name is Zeke and I'm the founder of [Keygen](https://keygen.sh). I haven't fully defined the company's open source values yet, but I have mentioned a few reasons I ended up going open source in [a blog post](https://keygen.sh/blog/all-your-licensing-are-belong-to-you/). Like Sentry, we try to monetarily support open source whenever possible (at a lesser scale than Sentry — but will continue growing that as we grow). I think putting in some time and really fleshing out our values will be on my todo list within the next few months. Excited to be a part of this conversation.

**Comment by morgante** [comment]
Hi there! I'm Morgante, the founder of [Grit](https://grit.io). We'd like to open source more of our software, but haven't decided on the right values and approach yet. I'm trying to be careful and diligent about this so whatever we commit to is maintainable long-term.

**Comment by dantelex** [comment]
Hey, there!

I'm Dante, founder of [Onboardbase](https://onboardbase.com/), a local-first secret infrastructure that gives teams automated compliance across developer machines and deployment environments. It's the first step towards collaborative security. 

We have open-sourced part of our solutions, we believe that for security to be really effective, it has to be both open and collaborative.

**Comment by chadwhitacre** [comment]
Welcome aboard, everyone! I've kicked out a few new issues to get some conversation going:

https://github.com/getsentry/loose-confederation/issues

Jump in where you like, in particular we should probably talk about what [outputs and outcomes](https://github.com/getsentry/loose-confederation/issues/5) we are all looking for here.

**Comment by chadwhitacre** [comment]
Gonna close this one out, we're off and running in #4. 💃
