### ISSUE TITLE
competing on any service

### ISSUE THREAD

**Issue by FlorianLudwig** [getsentry/loose-confederation#14]
Could you clarify what a "competing service" is?

Text from the draft:

> A Competing Use means use of the Software in or for a commercial product or service that competes with the Software or any other product or service we offer using the Software as of the date we make the Software available.

I worry that "competing on any service" could be interpreted quite broadly between companies in the tech sector.

When a company provides consulting, which might include consulting on using sentry, would that be competing? And therefor not allow that consulting company to use sentry?

What happens when sentry (the company) offers an important client to adapt some software for them? Would that mean sentry (the company) offers software development and any company offering software development is now offering a competing service and cannot use sentry (the software) anymore?
```[tasklist]
### Tasks
```

**Comment by chadwhitacre** [comment]
@gavin-zee @hmeeker Mind weighing in? Can you confirm that @mitsuhiko is [correct](https://github.com/getsentry/loose-confederation/issues/4#issuecomment-1816889834) that this is explicitly called out as a permitted use?

> in connection with software development services or managed services that you provide to a licensee using the Software in accordance with these Terms and Conditions.

**Comment by gavin-zee** [comment]
Yes, #4 of the permitted purposes was written exactly with the described scenario in mind to allow for service providers to provide consulting, development or similar services to users of the software.

**Comment by chadwhitacre** [comment]
Thanks @gavin-zee, closing. :)
